### PR TITLE
Fix error in team.go and time.go

### PR DESCRIPTION
**Pull request by scidomino**
The client was being lost in the call to gettype. I fixed them.

### CODE REVIEW

**Comment by mnovozhylov** [comment]
good catch Tomasso!

**Comment by scidomino** [comment]
No problem. There are two other issues that you probably should address
though they are not showstoppers:

1. All your endpoint modules define an extension of api.ApiClient (called
"a"). This is a problem because you are returning it from the .New()
method. Since it's lowercase it's not exported so you can't store it to a
typed variable. My coworker and I were actually surprised to learn that the
go compiler even allowed this.
2. All your endpoint modules functions are defined as acting on (r a) but
this means that a full copy of the object r is made each time the method is
called. You should define them on (r *a). Also, your .New() should return
*a instead of a.

Fortunately both of these changes can be made in a backwards compatible
way. I'd offer to do it but I'm running out of time on this project. Thanks!

-tom

**Comment by mnovozhylov** [comment]
@scidomino , thank you for your feedback
1. .New() returns "r", and "a" is local intentionally. Hope it explains the behavior of go compiler.
2. it was done to isolate every new call to the api as much as possible. I will check what we can do to reduce memory usage

**Comment by scidomino** [comment]
Ah. I see. Now that I study it further returning a local struct is legal in
go but is contraindicated in the google style guide. You don't work for
google so I guess that's a reasonable reason to ignore that bit of advice.
:) Anyhow, as I said before, it's not really a big deal either way. The
library is functional as it is. thanks!

-tom

**Comment by mnovozhylov** [comment]
"is contraindicated in the google style guide" - ohhh, that's interesting :)

**Comment by mnovozhylov** [comment]
@scidomino , you can try `experimental` branch that contains the requested changes

**Pull request merged**
